#!/usr/bin/env node
/**
 * Build both browser artifacts.
 *
 *   `lib/inline.js` — the head-served early hook: `src/policy.js` (export
 *   keywords stripped) + `src/inline.js`. Served by the Host half at
 *   `/remote-settings/early.js` and injected as a blocking head script, so it
 *   runs before the application bundle and can wrap the settings registration.
 *
 *   `lib/client.js` — the lazy-CJS bundle the module loader serves over
 *   `/plugins`, holding `src/policy.js` + `src/client.js` behind
 *   `window.__ModuleLoader__.load({ id, factory })`. Its factory body runs at
 *   materialization and carries the fallback repair.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const strip = (text) => text.replace(/^export /gm, '');
const policy = strip(await readFile(join(root, 'src/policy.js'), 'utf8'));
const inline = await readFile(join(root, 'src/inline.js'), 'utf8');
const client = await readFile(join(root, 'src/client.js'), 'utf8');

const inlineBanner = `/*
 * ${manifest.name} — early hook served at /remote-settings/early.js.
 * GENERATED by scripts/build.mjs from src/policy.js + src/inline.js.
 * Edit the sources and run \`npm run build\`; do not edit this file.
 */
`;
const inlineOut = `${inlineBanner}//#region src/policy.js\n${policy}\n//#endregion\n//#region src/inline.js\n${inline}\n//#endregion\n`;

const clientBanner = `/*
 * ${manifest.name} — browser client bundle (fallback lane).
 * GENERATED by scripts/build.mjs from src/policy.js + src/client.js.
 * Edit the sources and run \`npm run build\`; do not edit this file.
 */
`;
const clientOut = `${clientBanner}window.__ModuleLoader__.load({
\tid: ${JSON.stringify(manifest.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
//#region src/policy.js (factory copy)
${policy}
//#endregion
//#region src/client.js
${client}
//#endregion
\t\treturn module.exports;
\t}
});
`;

await writeFile(join(root, 'lib/inline.js'), inlineOut, 'utf8');
await writeFile(join(root, 'lib/client.js'), clientOut, 'utf8');
process.stdout.write(`built lib/inline.js (${inlineOut.length} bytes) and lib/client.js (${clientOut.length} bytes)\n`);
