#!/usr/bin/env node
/**
 * Build `lib/client.js` — the lazy-CJS browser bundle that
 * @deepseek-ai/dsh-client-modules snapshots and serves over `/plugins`.
 *
 * The bundle is one top-level script calling `window.__ModuleLoader__.load`.
 * Executing it only registers the factory; the module body runs at first
 * materialization. `src/client.js` is a plain script concatenated into that
 * factory, so it can call its own helpers directly and still `require('react')`
 * from the shell's frozen platform module table.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const client = await readFile(join(root, 'src/client.js'), 'utf8');

const banner = `/*
 * ${manifest.name} — browser client bundle.
 * GENERATED by scripts/build.mjs from src/client.js.
 * Edit the source and run \`npm run build\`; do not edit this file.
 */
`;

const header = `${banner}window.__ModuleLoader__.load({
\tid: ${JSON.stringify(manifest.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`;

const footer = `
\t\treturn module.exports;
\t}
});
`;

const out = `${header}\n//#region src/client.js\n${client}\n//#endregion\n${footer}`;

await writeFile(join(root, 'lib/client.js'), out, 'utf8');
process.stdout.write(`built lib/client.js (${out.length} bytes)\n`);
