#!/usr/bin/env node
/**
 * Build `lib/client.js` — the lazy-CJS browser bundle that
 * @deepseek-ai/dsh-client-modules snapshots and serves over `/plugins`.
 *
 * One top-level script calling `window.__ModuleLoader__.load`. Executing it
 * only registers the factory; the module body runs at first materialization.
 *
 * Two sources go inside the factory, concatenated in this order:
 *   1. `lib/zip.js` — the pure ZIP writer, with its `export` keywords stripped
 *      so its functions become factory-scope declarations. It stays a real ESM
 *      module on disk because `scripts/zip-check.mjs` imports it directly and
 *      validates the bytes it produces with an independent reader.
 *   2. `src/client.js` — the script that uses those functions.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const zip = (await readFile(join(root, 'lib/zip.js'), 'utf8')).replace(/^export /gm, '');
const client = await readFile(join(root, 'src/client.js'), 'utf8');

const banner = `/*
 * ${manifest.name} — browser client bundle.
 * GENERATED by scripts/build.mjs from lib/zip.js + src/client.js.
 * Edit the sources and run \`npm run build\`; do not edit this file.
 */
`;

const header = `${banner}window.__ModuleLoader__.load({
\tid: ${JSON.stringify(manifest.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`;

const footer = `
\t\treturn module.exports;
\t}
});
`;

const out = `${header}\n//#region lib/zip.js (inlined)\n${zip}\n//#endregion\n//#region src/client.js\n${client}\n//#endregion\n${footer}`;

await writeFile(join(root, 'lib/client.js'), out, 'utf8');
process.stdout.write(`built lib/client.js (${out.length} bytes)\n`);
